### PR TITLE
[Optional] A Few Bonus Files

### PR DESCRIPTION
**Pull request by cowanator**
- adding query sql
- github workflow (query update).
- Full Contract ABI
- a network config file.

### CODE REVIEW

**Comment by fleupold** [comment]
I understand this was [optional](https://forum.cow.fi/t/cow-grant-automate-mev-blocker-billing/2425), but does this mean we are not doing Milestone 3?

**Comment by cowanator** [comment]
It means that milestone 3 has been replaced with a few other more important things that took quite some time and weren't part of the original specification. For more details, I've outlined these changes and proposed the contents of this as an optional Milestone 4.

https://forum.cow.fi/t/cow-grant-automate-mev-blocker-billing/2425/7

**Comment by olgafetisova** [comment]
The queries are migrated to Dune, the PR is still open but mostly done.
The PR will address the following:
- adding query sql
- github workflow (query update).

**Comment by cowanator** [comment]
As for the last two points

- Full Contract ABI: This no longer seems important since we can always provide additional abi entries as needed https://github.com/cowdao-grants/mb-billing/blob/e08545eb5e41f49b7bf5f61baf8c9fdcebb4ec46/src/abis.ts#L1-L6

- The network config file is really only useful if you wanted to have fallback RPC urls and contract deployments to simplify some of the configuration parameters that are essentially permanent (like deployed contract addresses and a fallback RPC url). While this might still be of interest, this wouldn't be worth opening up a whole new grant proposal for. I would be happy to implement this if desired.

**Pull request closed without merging**
